resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: redis-operator
  newName: ""
commonAnnotations:
  redisDefaultImage: 'build-harbor.alauda.cn/:'
  redisExporterImage: 'build-harbor.alauda.cn/:'
  redisProxyImage: 'build-harbor.alauda.cn/:'
  redisShakeImage: 'build-harbor.alauda.cn/:'
  redisToolsImage: 'build-harbor.alauda.cn/:'
  redisVersion5Image: 'build-harbor.alauda.cn/:'
  redisVersion6Image: 'build-harbor.alauda.cn/:'
  redisVersion62Image: 'build-harbor.alauda.cn/:'
  redisVersion72Image: 'build-harbor.alauda.cn/:'
  redisVersion74Image: 'build-harbor.alauda.cn/:'
