/*
Copyright 2023 The RedisOperator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
)

// ServiceAccount is an autogenerated mock type for the ServiceAccount type
type ServiceAccount struct {
	mock.Mock
}

// CreateOrUpdateServiceAccount provides a mock function with given fields: ctx, namespace, sa
func (_m *ServiceAccount) CreateOrUpdateServiceAccount(ctx context.Context, namespace string, sa *v1.ServiceAccount) error {
	ret := _m.Called(ctx, namespace, sa)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateServiceAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1.ServiceAccount) error); ok {
		r0 = rf(ctx, namespace, sa)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateServiceAccount provides a mock function with given fields: ctx, namespace, sa
func (_m *ServiceAccount) CreateServiceAccount(ctx context.Context, namespace string, sa *v1.ServiceAccount) error {
	ret := _m.Called(ctx, namespace, sa)

	if len(ret) == 0 {
		panic("no return value specified for CreateServiceAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1.ServiceAccount) error); ok {
		r0 = rf(ctx, namespace, sa)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetServiceAccount provides a mock function with given fields: ctx, namespace, name
func (_m *ServiceAccount) GetServiceAccount(ctx context.Context, namespace string, name string) (*v1.ServiceAccount, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceAccount")
	}

	var r0 *v1.ServiceAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1.ServiceAccount, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.ServiceAccount); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ServiceAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceAccount creates a new instance of ServiceAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAccount {
	mock := &ServiceAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
