---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redis-middleware-alauda-io-v1-redisuser
  failurePolicy: Fail
  name: mredisuser.kb.io
  rules:
  - apiGroups:
    - redis.middleware.alauda.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redisusers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redis-middleware-alauda-io-v1-redisuser
  failurePolicy: Fail
  name: vredisuser.kb.io
  rules:
  - apiGroups:
    - redis.middleware.alauda.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - redisusers
  sideEffects: None
