
apiVersion: v1
kind: Service
metadata:
  name: redis-operator-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: redis-operator
