{
 "title": "Redis Dashboard",
 "description": "OwnerReference: operators/redis",
 "tags": [ "Redis" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "vmcluster",
    "label": "Kubernetes Cluster",
    "query": {
     "query": "label_values(redis_instance_info{role=\"master\"}, vmcluster)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(redis_instance_info{vmcluster=\"$vmcluster\",role=\"master\"}, namespace)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(redis_instance_info{vmcluster=\"$vmcluster\",role=\"master\", namespace=\"$Namespace\"}, service)"
    }
   },
   {
    "name": "Role",
    "query": {
     "query": "label_values(redis_instance_info{namespace=\"$Namespace\",vmcluster=\"$vmcluster\",service=~\"$Instance\"}, role)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(redis_instance_info{namespace=\"$Namespace\",vmcluster=\"$vmcluster\",service=~\"$Instance\",role=~\"$Role\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ClusterInfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(redis_connected_clients{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(redis_uptime_in_seconds{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(irate(redis_commands_processed_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[3m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Command calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max(irate(redis_commands_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\"}[3m])) by (cmd, service)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{cmd}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of Keys",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(redis_db_keys{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (db,pod)",
     "legendFormat": "{{pod}}#{{db}}"
    }
   ]
  },
  {
   "title": "PubSubChannels",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(redis_pubsub_channels{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PubSubPatterns",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(redis_pubsub_patterns{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Slow log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(redis_slowlog_length{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[3m])) by (pod)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{pod}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Keys Statistics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max(irate(redis_evicted_keys_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[3m])) by (pod)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{pod}}(Evicted)",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "max(irate(redis_expired_keys_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[3m])) by (pod)",
     "legendFormat": "{{pod}}(Expired)"
    }
   ]
  },
  {
   "title": "Keyspace Hit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(irate(redis_keyspace_hits_total{vmcluster=\"$vmcluster\",service=~\"$Instance\", namespace=\"$Namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Keyspace Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(irate(redis_keyspace_misses_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\"}[5m])) by (pod)",
     "legendFormat": " {{pod}}"
    }
   ]
  },
  {
   "title": "BlockedClients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max(redis_blocked_clients{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod) ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{pod}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Command statistics",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "avg(redis_commands_duration_seconds_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\"} / redis_commands_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\"}) by (cmd, service)"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Network I/O (Input)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(redis_net_input_bytes_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[5m])) by (pod)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{pod}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network I/O(Output)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_net_output_bytes_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cpu User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_cpu_user_seconds_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[5m])*100) by (pod)",
     "legendFormat": "{{pod}}(User)"
    },
    {
     "expr": "sum(irate(redis_cpu_user_children_seconds_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[5m]) * 100) by (pod)",
     "legendFormat": "{{pod}}(User[child])"
    }
   ]
  },
  {
   "title": "Cpu Sys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_cpu_sys_seconds_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[5m])*100) by (pod)",
     "legendFormat": "{{pod}}(Sys)"
    },
    {
     "expr": "sum(irate(redis_cpu_sys_children_seconds_total{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}[5m])*100) by (pod)",
     "legendFormat": "{{pod}}(Sys[child])"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "MemoryUsed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(redis_memory_used_bytes{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MemFragmentationRatio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "redis_memory_used_rss_bytes{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"} / redis_memory_used_bytes{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{pod}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MemoryUsed,Peek",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(redis_memory_used_peak_bytes{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MemoryMax",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(redis_memory_max_bytes{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "AOFRewriteInProgress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(redis_aof_rewrite_in_progress{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RDBBgsaveInProgress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(redis_rdb_bgsave_in_progress{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "AOFLastRewriteDuration",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(redis_aof_last_rewrite_duration_sec{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"} ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RDBLastSaveTime",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "max(redis_rdb_last_save_timestamp_seconds{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"} *1000 ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RDBLastBgsaveDuration",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(redis_rdb_last_bgsave_duration_sec{vmcluster=\"$vmcluster\",service=\"$Instance\", namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}