# permissions for end users to edit redissentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: databases-redissentinel-editor-role
rules:
- apiGroups:
  - databases
  resources:
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases
  resources:
  - redissentinels/status
  verbs:
  - get
