# permissions for end users to view redisusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisuser-viewer-role
rules:
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisusers/status
  verbs:
  - get
