# permissions for end users to edit redisusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisuser-editor-role
rules:
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisusers/status
  verbs:
  - get
