# permissions for end users to view redisclusterbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisclusterbackup-viewer-role
rules:
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisclusterbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisclusterbackups/status
  verbs:
  - get
