# permissions for end users to view redisfailovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisfailover-viewer-role
rules:
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisfailovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisfailovers/status
  verbs:
  - get
