# permissions for end users to edit redisclusterbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisclusterbackup-editor-role
rules:
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisclusterbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.middleware.alauda.io
  resources:
  - redisclusterbackups/status
  verbs:
  - get
