# permissions for end users to edit redisfailovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisfailover-editor-role
rules:
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisfailovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middle.alauda.cn
  resources:
  - redisfailovers/status
  verbs:
  - get
