apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: |
        This workspace is shared among all the pipeline tasks to read/write common resources
      name: source
    - name: config
  runTemplate:
    spec:
      workspaces:
        - name: config
          configmap:
            name: buildkitd-config
      taskRunSpecs:
        - pipelineTaskName: operator-arm64
          taskPodTemplate:
            nodeSelector:
              kubernetes.io/arch: arm64
            Tolerations:
              - key: build-arm
                operator: Exists
                effect: NoSchedule
        - pipelineTaskName: expose-arm64
          taskPodTemplate:
            nodeSelector:
              kubernetes.io/arch: arm64
            Tolerations:
              - key: build-arm
                operator: Exists
                effect: NoSchedule
        - pipelineTaskName: operator-arm64
          stepOverrides:
            - name: build
              resources:
                requests:
                  cpu: 1000m
                  memory: 2000Mi
                limits:
                  cpu: 2000m
                  memory: 4000Mi
            - name: push
              resources:
                requests:
                  cpu: 1000m
                  memory: 2000Mi
                limits:
                  cpu: 2000m
                  memory: 4000Mi
        - pipelineTaskName: bundle-arm64
          taskPodTemplate:
            nodeSelector:
              kubernetes.io/arch: arm64
            Tolerations:
              - key: build-arm
                operator: Exists
                effect: NoSchedule
        - pipelineTaskName: bundle-operator
          stepOverrides:
            - name: update-version-data
              resources:
                requests:
                  cpu: 666m
                  memory: 1333Mi
                limits:
                  cpu: 2000m
                  memory: 4000Mi
            - name: generate-related-images
              resources:
                requests:
                  cpu: 666m
                  memory: 1333Mi
                limits:
                  cpu: 2000m
                  memory: 4000Mi
            - name: operator-bundle
              resources:
                requests:
                  cpu: 668m
                  memory: 1334Mi
                limits:
                  cpu: 2000m
                  memory: 4000Mi
        - pipelineTaskName: operator-amd64
          stepOverrides:
            - name: build
              resources:
                requests:
                  cpu: 1000m
                  memory: 2000Mi
                limits:
                  cpu: 2000m
                  memory: 4000Mi
            - name: push
              resources:
                requests:
                  cpu: 1000m
                  memory: 2000Mi
                limits:
                  cpu: 2000m
                  memory: 4000Mi
        - pipelineTaskName: go-test
          stepOverrides:
            - name: prepare
              resources:
                requests:
                  cpu: 500m
                  memory: 1000Mi
                limits:
                  cpu: 1500m
                  memory: 3000Mi
            - name: test
              resources:
                requests:
                  cpu: 500m
                  memory: 1000Mi
                limits:
                  cpu: 1500m
                  memory: 3000Mi
            - name: analysis
              resources:
                requests:
                  cpu: 500m
                  memory: 1000Mi
                limits:
                  cpu: 1500m
                  memory: 3000Mi
        - pipelineTaskName: operator-merge
          stepOverrides:
            - name: merge
              resources:
                requests:
                  cpu: 1000m
                  memory: 2000Mi
                limits:
                  cpu: 1000m
                  memory: 2000Mi
  tasks:
    - name: operator-amd64
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: build-image-buildkit
      workspaces:
        - name: source
          workspace: source
        - name: config
          workspace: config
      params:
        - name: container-images
          value:
            - build-harbor.alauda.cn/middleware/redis-operator
        - name: dockerfile
          value: build/Dockerfile
        - name: labels
          value:
            - branch=$(build.git.branch.name)
            - commit=$(build.git.lastCommit.id)
    - name: operator-arm64
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: build-image-buildkit
      workspaces:
        - name: source
          workspace: source
        - name: config
          workspace: config
      params:
        - name: container-images
          value:
            - build-harbor.alauda.cn/middleware/redis-operator
        - name: dockerfile
          value: build/Dockerfile
        - name: labels
          value:
            - branch=$(build.git.branch.name)
            - commit=$(build.git.lastCommit.id)
    - name: operator-merge
      runAfter:
        - operator-amd64
        - operator-arm64
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: merge-image-buildkit
      workspaces:
        - name: source
          workspace: source
      params:
        - name: container-images
          value:
            - build-harbor.alauda.cn/middleware/redis-operator:$(build.git.version.docker)
        - name: dockerfile
          value: build/Dockerfile
        - name: source-image-digests
          value:
            - $(tasks.operator-amd64.results.ociContainerImageBuild-url)
            - $(tasks.operator-arm64.results.ociContainerImageBuild-url)
  finally:
    - name: release-tag
      when:
        - input: "$(build.git.versionPhase)"
          operator: in
          values:
            - custom
            - ga
        - input: $(tasks.status)
          operator: in
          values:
            - Succeeded
            - Completed
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: alauda-release-tag
      workspaces:
        - name: source
          workspace: source
      params:
        - name: version
          value: $(build.git.version.docker)
