apiVersion: redis.middleware.alauda.io/v1
kind: RedisBackup
metadata:
  labels:
    redisfailovers.databases.spotahome.com/name: redissentinel
  name: redissentinel-1
spec:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  source:
    redisFailoverName: redissentinel
    storageClassName: gp3
  storage: 1Gi
