# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/databases.spotahome.com_redisfailovers.yaml
- bases/databases.spotahome.com_redissentinels.yaml
- bases/redis.kun_distributedredisclusters.yaml
- bases/redis.middleware.alauda.io_redisusers.yaml
- bases/middleware.alauda.io_redis.yaml
- bases/middleware.alauda.io_imageversions.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_redisfailovers.yaml
#- path: patches/webhook_in_distributedredisclusters.yaml
#- path: patches/webhook_in_redis.yaml
#- path: patches/webhook_in_redisusers.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_redisfailovers.yaml
#- path: patches/cainjection_in_distributedredisclusters.yaml
#- path: patches/cainjection_in_redis.yaml
#- path: patches/cainjection_in_redisusers.yaml
#- path: patches/cainjection_in_databases_redissentinels.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
