# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/databases.spotahome.com_redisfailovers.yaml
- bases/redis.kun_distributedredisclusters.yaml
- bases/redis.middleware.alauda.io_redisbackups.yaml
- bases/redis.middleware.alauda.io_redisclusterbackups.yaml
- bases/redis.middleware.alauda.io_redisusers.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_redisfailovers.yaml
#- patches/webhook_in_redisbackups.yaml
#- patches/webhook_in_distributedredisclusters.yaml
#- patches/webhook_in_redisclusterbackups.yaml
#- patches/webhook_in_redisusers.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_redisfailovers.yaml
#- patches/cainjection_in_redisbackups.yaml
#- patches/cainjection_in_distributedredisclusters.yaml
#- patches/cainjection_in_redisclusterbackups.yaml
#- patches/cainjection_in_redisusers.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
