Service:
  RegionId: ap-southeast-1
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      HelmChartArtifactRelation:
        '{{computenest::helmchart::chartUrl}}': 
          ArtifactId: ${Artifact.Chart.ArtifactId}
          ArtifactVersion: ${Artifact.Chart.ArtifactVersion}
    AcrImageArtifactRelation:
        '{{ computenest::acrimage::redis6 }}': 
          ArtifactId: ${Artifact.Redis6.ArtifactId}
          ArtifactVersion: ${Artifact.Redis6.ArtifactVersion}
        '{{ computenest::acrimage::redis72 }}': 
          ArtifactId: ${Artifact.Redis72.ArtifactId}
          ArtifactVersion: ${Artifact.Redis72.ArtifactVersion}

    TemplateConfigs:
      - Name: Deploy Redis Instance
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    Image: 'resources/icons/service_logo.png'
    Name: RedisOperator 部署
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Redis6:
    ArtifactType: AcrImage
    ArtifactName: redis-image-6
    Description: Redis 6 image
    ArtifactProperty:
      RepoName: "middleware/redis"
      Tag: 6.0-alpine
  Redis72:
    ArtifactType: AcrImage
    ArtifactName: redis-image-7-2
    Description: Redis 7.2 image
    ArtifactProperty:
      RepoName: "middleware/redis"
      Tag: 7.2-alpine
  Chart:
    ArtifactType: HelmChart
    ArtifactName: redis-operator-chart
    Description: Redis Operator 部署物
    ArtifactProperty:
      RepoName: ${HelmChartBuilder.Chart.RepoName}
      Tag: ${HelmChartBuilder.Chart.Tag}
HelmChartBuilder:
  Chart:
    HelmChartPath: 'resources/artifact_resources/helm_chart/redis-operator-chart-3.18.0.tgz'
    RepoName: redis-operator-chart
    Tag: 3.18.0