Service:
  RegionId: ap-southeast-1
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      HelmChartArtifactRelation:
        '{{computenest::helmchart::chartUrl}}': 
          ArtifactId: ${Artifact.ArtifactRedisOperatorChart.ArtifactId}
          ArtifactVersion: ${Artifact.ArtifactRedisOperatorChart.ArtifactVersion}
    TemplateConfigs:
      - Name: Deploy Redis Instance
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    Image: 'resources/icons/service_logo.png'
    Name: RedisOperator 部署
  ShareType: Public
  ApprovalType: Manual
Artifact:
  ArtifactRedisOperatorChart:
    ArtifactType: HelmChart
    ArtifactName: redis-operator-chart
    Description: Redis Operator 部署物
    ArtifactProperty:
      RepoName: ${HelmChartBuilder.HelmChart_1.RepoName}
      Tag: ${HelmChartBuilder.HelmChart_1.Tag}
    ArtifactProperty:
      RepoName: ${HelmChartBuilder.RedisOperatorChart.RepoName}
      Tag: ${HelmChartBuilder.RedisOperatorChart.Tag}
HelmChartBuilder:
  RedisOperatorChart:
    HelmChartPath: 'resources/artifact_resources/helm_chart/redis-operator-chart-3.18.0.tgz'
    RepoName: redis-operator-chart
    Tag: 3.18.0