Service:
  RegionId: ap-southeast-1
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      HelmChartArtifactRelation:
        '{{ computenest::helmchart::redis-operator }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
    - Name: 容器集群版
      Url: 'ros_templates/template.yaml'
      AllowedRegions:
      - ap-southeast-1
  ServiceType: private
  ServiceInfo:
  - Locale: zh-CN
    Name: alauda/redis-operator-2gv0
    ShortDescription: Servicedescription
    Image: 
      https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1853370294850618/service-image/bfd30cc4-e959-4093-b5cb-77a05058b911.png
    Softwares: []
Artifact:
  Artifact_1:
    ArtifactType: HelmChart
    ArtifactName: redis-operator-helm-chart
    ArtifactProperty:
      RepoName: ${HelmChartBuilder.HelmChart_1.RepoName}
      Tag: ${HelmChartBuilder.HelmChart_1.Tag}
      RepoType: Public
HelmChartBuilder:
  HelmChart_1:
    HelmChartPath: 'resources/artifact_resources/helm_chart/redis-operator-1.0.1-3.tgz'
    RepoName: redis-operator
    Tag: 1.0.1-3
