name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Get the current tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: GitHub Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./Dockerfile
        context: .
        push: true
        tags: |
          ${{ secret.DOCKER_USERNAME }}/redis-operator:${{ env.TAG }}
          ghcr.io/alauda/redis-operator:${{ env.TAG }}
        platforms: linux/amd64,linux/arm64
